# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [2]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [6]:
city = pd.read_csv ("cities.csv")

city

,Unnamed: 0,City,Lat,Lng,Temp F,Max Temp F,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,bluff,-46.60,168.33,46.99,46.99,93,100,3.00,NZ,1599929950
1,1,carnarvon,-24.87,113.63,64.40,64.40,72,13,17.22,AU,1599929951
2,2,muros,42.78,-9.06,82.99,82.99,51,65,1.99,ES,1599929951
3,3,esperance,-33.87,121.90,44.60,44.60,100,1,6.93,AU,1599929951
4,4,hermanus,-34.42,19.23,62.01,62.01,78,0,11.18,ZA,1599929952
...,...,...,...,...,...,...,...,...,...,...,...
593,593,dakar,14.69,-17.44,84.20,84.20,79,40,16.11,SN,1599929976
594,594,yumen,40.28,97.20,52.34,52.34,37,0,9.40,CN,1599930174
595,595,fairbanks,64.84,-147.72,38.43,39.99,86,75,1.88,US,1599929961
596,596,kristiansund,63.11,7.73,50.00,50.00,61,71,27.51,NO,1599930174
597,597,pingliang,35.54,106.69,61.11,61.11,74,75,3.67,CN,1599930174

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [13]:
# Configure gmaps with API key
gmaps.configure(api_key=g_key)

locations = city[["Lat", "Lng"]]

weight = city["Humidity"]

maps = gmaps.figure()

In [14]:
heatlayer = gmaps.heatmap_layer(locations, weights=weight, 
                                 dissipating=True, max_intensity=100,
                                 point_radius = 1)

maps.add_layer(heatlayer)

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [15]:
c1 = cities.loc[cities['Max Temp F']<77]
c2 = cond1.loc[cond1['Max Temp F']>64]
c3 = cond2.loc[cond2['Cloudiness']>40]
c4 = cond3.loc[cond3['Cloudiness']<70]
c5 = cond4.loc[cond4['Wind Speed']<10]
fit = cond5.reset_index(drop=True)
fit

NameError: name 'cities' is not defined

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map


# Display figure